project: 
  type: website
  output-dir: docs
  
website:
  title: "Lauren Stiles"
  navbar: 
    left: 
      - href: index.qmd
        text: Home 
      - href: Ecological interests.qmd
        text: Ecology
      - href: Fun.qmd
        text: Fun
      
format: 
  html: 
    theme:  
      - mystyles.scss
    mainfont: Courier Prime
    toc: true 
    page-layout: full
